const express = require('express');
const router = express.Router();
const roomController = require('../controllers/roomController');
const participantController = require('../controllers/participantController');
const itemController = require('../controllers/itemController');
const bidController = require('../controllers/bidController');

router.get('/', roomController.getRooms);
router.post('/', roomController.createRoom);
router.delete('/:roomId', roomController.deleteRoom);
router.get('/:roomId', roomController.getRoom);
router.post('/:roomId/categories', roomController.addRoomCategory);
router.delete('/:roomId/categories/:categoryId', roomController.deleteRoomCategory);
router.post('/:roomId/participants', participantController.addParticipant);
router.patch('/:roomId/participants/:participantId', roomController.updateParticipant);
router.post('/:roomId/items', itemController.addItem);
router.patch('/:roomId/items/:itemId', roomController.updateItem);
router.delete('/:roomId/items/:itemId', roomController.deleteItem);
router.post('/:roomId/items/:itemId/reassign', roomController.reassignItem);
router.post('/:roomId/start', roomController.startAuction);
router.post('/:roomId/select-item', roomController.selectItem);
router.post('/:roomId/stop-item', roomController.stopCurrentItem);
router.post('/:roomId/auto', roomController.configureAutoAuction);
router.post('/:roomId/restart', roomController.restartAuction);
router.post('/:roomId/previous', roomController.previousItem);
router.post('/:roomId/end', roomController.endAuction);
router.post('/:roomId/next', roomController.nextItem);
router.post('/:roomId/skip', roomController.skipItem);
router.post('/:roomId/bids', bidController.placeBid);

module.exports = router;
